import os
import json
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from flask import current_app
import asyncio
from playwright.async_api import async_playwright
from typing import Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

class ReportServiceTwo:
    def __init__(self):
        # Determine paths relative to the current file's location
        backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
        self.data_dir = os.path.join(backend_dir, 'data')
        self.templates_dir = os.path.join(backend_dir, 'templates')
        # Add project root to the Jinja2 loader path to find report_template.html
        self.env = Environment(loader=FileSystemLoader(self.templates_dir))

    async def generate_pdf_report(self, scan_id: str, user_name: str, user_email: str ,user_token: Optional[str] = None) -> str:
        """
        Generates a PDF report from HTML template using Playwright.
        """
        try:
            print(f"[ReportServiceTwo] Generating PDF report for scan_id={scan_id}")
            
            # 1. Load scan results
            scan_results = self._load_scan_results(scan_id)
            print(f"[ReportServiceTwo] Loaded scan results for {scan_id}")

            # 2. Load and render HTML template
            template = self.env.get_template('report_template.html')
            
           
            
            # Prepare data for rendering
            render_data = {
                "report": {
                    "Repo_name": scan_results.get("Repository_name"), # Include repository name in report metadata
                    "title": "Security Analysis Report",
                    "scan_id": scan_results.get("scan_id"),
                    "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "name": "Generated by Backstage Rookie",
                    "provider": {
                        "name": "Backstage Rookie",
                        "address": "contact - swarajdarekar9@gmail.com "
                    },
                    "client": {
                        "name": user_name,
                        "address": user_email
                    },
                    "version": "1.0.0"
                },
                "executive_summary": scan_results.get("executive_summary", {}),
                "methodology": scan_results.get("methodology", {}),
                "findings": scan_results.get("findings", []),
                "metrics": {
                    "total_findings": scan_results.get("total_findings", 0),
                    "severity_distribution": scan_results.get("executive_summary", {}).get("severity_distribution", {})
                },
                "framework_analysis": scan_results.get("framework_analysis", {}),
                "disclaimer": {"text": "This report is generated by an automated security analysis tool."},
                "appendix": {"static_section": "Further details can be found in the raw scan results JSON.", "tool_output": "N/A"},
                "BRadvice": scan_results.get("BRadvice", {}).get("BRadvice", {}) # Include BRadvice in render_data
            }
            
            # Render the template to HTML
            rendered_html = template.render(render_data)
            
            # 3. Save rendered HTML to a temporary file
            temp_html_path = os.path.join(self.data_dir, f"temp_report_{scan_id}.html")
            with open(temp_html_path, "w", encoding="utf-8") as f:
                f.write(rendered_html)
            print(f"[ReportServiceTwo] Rendered HTML saved to {temp_html_path}")

            # 4. Convert HTML to PDF using Playwright
            pdf_path = os.path.join(self.data_dir, 'generated_reports', f"report_{scan_id}.pdf")
            os.makedirs(os.path.dirname(pdf_path), exist_ok=True) # Ensure dir exists

            async with async_playwright() as p:
                browser = await p.chromium.launch()
                page = await browser.new_page()
                await page.goto(f"file:///{os.path.abspath(temp_html_path)}") # Load local HTML file
                await page.pdf(path=pdf_path)
                await browser.close()
            print(f"[ReportServiceTwo] PDF report generated: {pdf_path}")

            # 5. Clean up temporary HTML file
            os.remove(temp_html_path)
            
            return pdf_path

        except Exception as e:
            print(f"[ReportServiceTwo] Error generating PDF report: {e}")
            raise

    def _load_scan_results(self, scan_id: str) -> Dict[str, Any]:
        """Loads scan results from storage."""
        results_path = os.path.join(self.data_dir, 'scanned_results', f'{scan_id}.json')
        if not os.path.exists(results_path):
            raise FileNotFoundError(f"Scan results not found for ID: {scan_id}")
        with open(results_path, 'r', encoding='utf-8') as f:
            return json.load(f)
